services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

  auth:
    build: .
    container_name: devops-1
    ports:
      - "3000:3000"
    environment:
      - JWT_KEY=mysecretkey
      - MONGO_URI=mongodb://mongo:27017/auth
    depends_on:
      - mongo

