apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-1
  template:
    metadata:
      labels:
        app: devops-1
    spec:
      containers:
      - name: devops-1
        image: devops-1:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: JWT_KEY
          value: "mysecret"
        
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/auth"
